/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class GameViewUI extends View {
		public rightBtn:Laya.Button;
		public leftBtn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameView");
        }
    }
    REG("ui.GameViewUI",GameViewUI);
    export class LoadingUI extends View {
		public bg:Laya.Image;
		public progress:Laya.ProgressBar;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Loading");
        }
    }
    REG("ui.LoadingUI",LoadingUI);
}