/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./GameView"
import Index from "./Index"
import LoadingRT from "./LoadingRT"
import LoseView from "./views/LoseView"
import VictoryView from "./views/VictoryView"
import BulletPrefab from "./prefab/BulletPrefab"
import MonsterPrefab from "./prefab/MonsterPrefab"
import RolePrefab from "./prefab/RolePrefab"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("GameView.ts",GameView);
        reg("Index.ts",Index);
        reg("LoadingRT.ts",LoadingRT);
        reg("views/LoseView.ts",LoseView);
        reg("views/VictoryView.ts",VictoryView);
        reg("prefab/BulletPrefab.ts",BulletPrefab);
        reg("prefab/MonsterPrefab.ts",MonsterPrefab);
        reg("prefab/RolePrefab.ts",RolePrefab);
    }
}
GameConfig.init();