/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Index from "./Index"
import LoadingRT from "./LoadingRT"
import PhysicsGameMainRT from "./scence/physicsDemo/PhysicsGameMainRT"
import CloseBtn from "./prefab/CloseBtn"
import PhysicsGameMain from "./scence/physicsDemo/PhysicsGameMain"
import Bullet from "./prefab/Bullet"
import DropBox from "./prefab/DropBox"
import LoopImg from "./prefab/LoopImg"
import Role from "./prefab/Role"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1334;
    static height:number=750;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Index.ts",Index);
        reg("LoadingRT.ts",LoadingRT);
        reg("scence/physicsDemo/PhysicsGameMainRT.ts",PhysicsGameMainRT);
        reg("prefab/CloseBtn.ts",CloseBtn);
        reg("scence/physicsDemo/PhysicsGameMain.ts",PhysicsGameMain);
        reg("prefab/Bullet.ts",Bullet);
        reg("prefab/DropBox.ts",DropBox);
        reg("prefab/LoopImg.ts",LoopImg);
        reg("prefab/Role.ts",Role);
    }
}
GameConfig.init();