/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./GameView"
import Index from "./Index"
import LoadingRT from "./LoadingRT"
import PhysicsGameMainRT from "./scence/physicsDemo/PhysicsGameMainRT"
import PhysicsGameMain from "./scence/physicsDemo/PhysicsGameMain"
import Bullet from "./prefab/Bullet"
import BulletPrefab from "./prefab/BulletPrefab"
import DropBox from "./prefab/DropBox"
import MonsterPrefab from "./prefab/MonsterPrefab"
import Role from "./prefab/Role"
import RolePrefab from "./prefab/RolePrefab"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1334;
    static height:number=750;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("GameView.ts",GameView);
        reg("Index.ts",Index);
        reg("LoadingRT.ts",LoadingRT);
        reg("scence/physicsDemo/PhysicsGameMainRT.ts",PhysicsGameMainRT);
        reg("scence/physicsDemo/PhysicsGameMain.ts",PhysicsGameMain);
        reg("prefab/Bullet.ts",Bullet);
        reg("prefab/BulletPrefab.ts",BulletPrefab);
        reg("prefab/DropBox.ts",DropBox);
        reg("prefab/MonsterPrefab.ts",MonsterPrefab);
        reg("prefab/Role.ts",Role);
        reg("prefab/RolePrefab.ts",RolePrefab);
    }
}
GameConfig.init();